# Generated by Django 4.2.13 on 2024-05-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
