# Generated by Django 4.2.13 on 2024-07-02 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("shipping_address", models.TextField()),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=7)),
                ("date_ordered", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="address_1",
            new_name="shipping_address1",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="address_2",
            new_name="shipping_address2",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="city",
            new_name="shipping_city",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="country",
            new_name="shipping_country",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="email",
            new_name="shipping_email",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="fullname",
            new_name="shipping_fullname",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="state",
            new_name="shipping_state",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="zipcode",
            new_name="shipping_zipcode",
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payment.order"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
