# Generated by Django 4.2.13 on 2024-07-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payment",
            "0003_orderitem_price_orderitem_product_orderitem_quantity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipped",
            field=models.BooleanField(default=False),
        ),
    ]
