# Generated by Django 4.2.13 on 2024-06-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_category_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="user",
        ),
    ]
