# Generated by Django 4.2.13 on 2024-06-23 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_alter_category_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="user",
        ),
    ]
