# Generated by Django 4.2.13 on 2024-07-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0009_category_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="user",
        ),
    ]
